name: Create a comment on new issues

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions: write-all

jobs:
  print-with-action:
    runs-on: ubuntu-latest
    steps:
      - name: "hello world"
        run: echo 'Hello world!'
        shell: bash
